### ISSUE TITLE
Remove magic numbers

### ISSUE THREAD

**Issue by motiwari** [d1ngn1gefe1/momatools#5]
[Magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) are an anti-pattern -- it makes code hard to read, and requires every instance for the magic number to be updated if it should be changed.. It's better to move these to a `constants.py` file and import them everywhere.

[Examples](https://github.com/d1ngn1gefe1/momatools/blob/main/preproc/ann_phase1.py#L63-L82)

**Comment by d1ngn1gefe1** [comment]
These magic numbers mainly show up `preproc`. The [`preproc`](https://github.com/d1ngn1gefe1/momatools/tree/main/preproc) directory is only needed for data pre-processing and should be made internal/private. 

@zanedurante @linden-li Shall we create a separate GitHub repo? Is there a better way of making some directories private.

**Comment by linden-li** [comment]
> @zanedurante @linden-li Shall we create a separate GitHub repo? Is there a better way of making some directories private.
Yes, we can create a separate GitHub repo for data preparation and cleaning. We'll be releasing the cleaned annotations publicly anyway.

**Comment by linden-li** [comment]
@d1ngn1gefe1 Making this as done, since you made them private variables.
